config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#show_issues'

  resources :issues do
    resources :comments
  end
  resources :statuses
  resources :users do
    resources :issues
  end
  resources :projects
  resources :groups do
    resources :users
  end

  get '/issues/:id/edit_status' => 'issues#edit_status', as: 'edit_issue_status'
  put '/issues/:id/change_status' => 'issues#change_status', as: 'change_issue_status'
  put '/working_ons/:id/change_assignee' => 'working_ons#change_assignee', as: 'change_assignee'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'users/:id/show_issues' => 'users#show_issues', as: 'show_issues'
end

app/models/issue.rb
class Issue < ApplicationRecord
  default_scope { order(priority: :desc) }
  belongs_to :project
  belongs_to :status
  has_many :comments, :dependent => :destroy
  has_one :working_on, :dependent => :destroy
  has_one :user, through: :working_on
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :priority, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
  validates :status, presence: true
  validates :project, presence: true
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  load_and_authorize_resource
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :edit_status, :change_status]
  before_filter :authorize
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @substatuses = Array.new
    @substatuses = @substatuses.append(@issue.status)
    @substatuses = @substatuses|@issue.status.substatuses
    @issue_user_id = nil
    if (!@issue.user.nil?)
      @issue_user_id = @issue.user.id
    end
    @comments = Comment.where(issue_id: @issue.id).order('created_at DESC')
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_status
  end

  def change_status
    substatuses = @issue.status.substatuses
    if !substatuses.nil?
      allowed_statuses = substatuses.map { |status| status.id }
      params.permit[:status_id]
      wanted_status_id = params[:status_id].to_i
      if allowed_statuses.include? wanted_status_id
        respond_to do |format|
          if @issue.update_attribute(:status_id, wanted_status_id)
            format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
            format.json { render :show, status: :ok, location: @issue }
          else
            format.html { render :edit }
            format.json { render json: @issue.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_issue
    @issue = Issue.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def issue_params
    params.require(:issue).permit(:name, :description, :priority, :project_id, :status_id)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(issue, html: {class: 'centered'}) do |f| %>
        <% if issue.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger">
                <%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:
              </div>
              <ul>
                <% issue.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :priority %>
          <%= f.select :priority, options_for_select(0..5, selected: 0), {}, {class: 'form-control'} %>
        </div>

        <div class="form-group">
          <%= f.label :project %>
          <%= f.collection_select :project_id, Project.order(:name), :id, :name, {prompt: 'Select project'}, {class: 'form-control'} %>
        </div>

        <div class="form-group">
          <%= f.label :status %>
          <%= f.collection_select :status_id, Status.order(:name), :id, :name, {prompt: 'Select status'}, {class: 'form-control'} %>
        </div>

        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
        <% if issue.id.nil? %>
            <%= link_to 'Cancel', issues_path, :class => "btn btn-default" %>
        <% else %>
            <%= link_to 'Cancel', issue_path(issue), :class => "btn btn-default" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

app/views/issues/edit_status.html.erb
<h1>Editing Status</h1>
<%= form_for(@issue, :url => change_issue_status_path(@issue)) do |f| %>

    <div>
      <%= f.label :status %>
      <%= f.collection_select :status_id, Status.order(:name), :id, :name, {prompt: 'Select team'}, {class: 'form-control'} %>
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
<% end %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table class="table table-hover table-responsive">
  <thead>
  <tr>
    <th>Issue name</th>
    <th>Priority</th>
    <th>Project</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.name %></td>
        <td><%= issue.priority %></td>
        <% if !issue.project.nil? %>
            <td><%= issue.project.name %></td>
            <td><%= issue.status.name %></td>
        <% end %>
        <td><%= link_to 'Show', issue, :class => "btn btn-default" %>
          <%= link_to 'Edit', edit_issue_path(issue), :class => "btn btn-default" %>
          <% if can? :delete, issue %>
              <%= link_to 'Destroy', issue, :class => "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path, :class => "btn btn-primary" %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @issue.name %>
</h1>

<div class="row">
  <div class="col-xs-3 col-sm-2 ">
    <p>
      <strong>Project:</strong>
    </p>
  </div>
  <div class="col-xs-9 col-sm-10">
    <p><%= @issue.project.name %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-2 ">
    <p>
      <strong>Priority:</strong>
    </p>
  </div>
  <div class="col-xs-9 col-sm-10">
    <p><%= @issue.priority %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-2 ">
    <p>
      <strong>Status:</strong>
    </p>
  </div>
  <div class="col-xs-9 col-sm-10">
    <p><%= select_tag :status_id, options_for_select(@substatuses.map { |k| [k.name, k.id] }, selected: @issue.status.name), :class => "issue_status" %>
      <button class="btn btn-default submit hidden status">Change status</button>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-2 ">
    <p><strong>Assignee</strong></p>
  </div>
  <div class="col-xs-9 col-sm-10">
    <p><%= select_tag :user_id, options_for_select(User.all.map { |k| [k.username, k.id] }, selected: @issue_user_id), :include_blank => true, :class => 'assignee_select' %>
      <button class="btn btn-default submit hidden assignee">Change assignee</button>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-2">
    <p><strong>Description:</strong></p>
  </div>
  <div class="col-xs-9 col-sm-10">
    <p><%= @issue.description %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-3 col-sm-2">
    <% if can? :update, @issue %>
        <p><strong>Actions:</strong></p>
    <% end %>
  </div>
  <div class="col-xs-9 col-sm-10">
    <% if can? :update, @issue %>
        <p><%= link_to 'Edit', edit_issue_path(@issue), :class => "btn btn-default" %>
    <% end %>
    <% if can? :delete, @issue %>
        <td><%= link_to 'Destroy', @issue, :class => "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
    <% end %>
    </p>
  </div>
</div>

<%= render 'comments/comment' %>
<script>
    $(document).ready(function () {
        $(".assignee_select").select2({
            placeholder: "Select user"
        });

        $('.issue_status').select2({
            minimumResultsForSearch: Infinity
        });
    });
</script>
<script>
    $(function () {
        var $select = $('.issue_status'),
            $submit = $('.submit.status');

        $select.on('change', function () {
            if ($(this).val() != '<%= @issue.status.id %>') {
                $submit.removeClass('hidden');
            } else {
                $submit.addClass('hidden');
            }
        });

        $submit.click(function () {
            var selected = $select.val();

            $.ajax({
                type: "PUT",
                url: "<%= change_issue_status_path(@issue) %>",
                data: {status_id: selected},
                success: function (data) {
                    $submit.hide();
                }
            });
        });
    });
</script>
<script>
    $(function () {
        var $select = $('.assignee_select'),
            $submit = $('.submit.assignee');

        $select.on('change', function () {
            if ($(this).val() != '<%= @issue.user.nil? ? "" : @issue.user.id %>') {
                $submit.removeClass('hidden');
            } else {
                $submit.addClass('hidden');
            }
        });

        $submit.click(function () {
            var selected = $select.val();

            $.ajax({
                type: "PUT",
                url: "<%= change_assignee_path %>",
                data: {issue_id: '<%=@issue.id%>', user_id: selected},
                success: function (data) {
                    $submit.hide();
                }
            });
        });
    });
</script>