config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#show_issues'

  resources :issues do
    resources :comments
  end
  resources :statuses
  resources :users do
    resources :issues
  end
  resources :projects
  resources :groups do
    resources :users
  end

  get '/issues/:id/edit_status' => 'issues#edit_status', as: 'edit_issue_status'
  put '/issues/:id/change_status' => 'issues#change_status', as: 'change_issue_status'
  put '/working_ons/:id/change_assignee' => 'working_ons#change_assignee', as: 'change_assignee'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'users/:id/show_issues' => 'users#show_issues', as: 'show_issues'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, :dependent => :nullify
  validates :name, presence: true, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(group, html: {class: 'centered'}) do |f| %>
        <% if group.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger">
                <%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:
              </div>

              <ul>
                <% group.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>

        <% if group.id.nil? %>
            <%= link_to 'Cancel', groups_path, :class => "btn btn-default" %>
        <% else %>
            <%= link_to 'Cancel', group_path(group), :class => "btn btn-default" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing Team</h1>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team</h1>

<table class="table table-hover table-responsive">
  <thead>
  <tr>
    <th>Team name</th>
    <% if can? :update, Group %>
        <th>Actions</th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group) %></td>
        <td>
          <% if can? :update, group %>
              <%= link_to 'Edit', edit_group_path(group), :class => "btn btn-default" %>
          <% end %>
          <% if can? :delete, group %>
              <%= link_to 'Destroy', group, :class => "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path, :class => "btn btn-primary" %>

app/views/groups/new.html.erb
<h1>New Team</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <%= @group.name %>
</h1>

<h3>
  <strong>Users:</strong>
</h3>
<table class="table table-hover table-responsive">
  <thead>
  <tr>
    <th>Username</th>
  </tr>
  </thead>

  <tbody>
  <% @group.users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user_path(user) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<h3>
  <strong>Working ons:</strong>
</h3>
<table class="table table-hover table-responsive">
  <thead>
  <tr>
    <th>User</th>
    <th>Issue</th>
    <th>Priority</th>
    <th>Issue Status</th>
  </tr>
  </thead>

  <tbody>
  <% @group.users.each do |user| %>
      <% user.issues.each do |issue| %>
          <tr>
            <td><%= link_to user.username, user_path(user) %></td>
            <td><%= link_to issue.name, issue_path(issue) %></td>
            <td><%= issue.priority%></td>
            <td><%= issue.status.name%></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>