config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#show_issues'

  resources :issues do
    resources :comments
  end
  resources :statuses
  resources :users do
    resources :issues
  end
  resources :projects
  resources :groups do
    resources :users
  end

  get '/issues/:id/edit_status' => 'issues#edit_status', as: 'edit_issue_status'
  put '/issues/:id/change_status' => 'issues#change_status', as: 'change_issue_status'
  put '/working_ons/:id/change_assignee' => 'working_ons#change_assignee', as: 'change_assignee'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'users/:id/show_issues' => 'users#show_issues', as: 'show_issues'
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group, optional:true
  has_many :working_ons, :dependent => :destroy
  has_many :issues, through: :working_ons
  has_secure_password
  validates :username, presence: true, uniqueness: true, length: { maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_issues
    if current_user.nil?
      redirect_to '/login'
    else
      @user = current_user
      @issues = @user.issues
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :group_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user, html:{class: 'centered'}) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :team %>
      <%= f.collection_select :group_id, Group.order(:name), :id, :name, {prompt: 'Select team'}, {class: 'form-control'}%>
    </div>

    <br>
    <button type="submit" class="btn btn-default">Submit</button>
    <%= link_to 'Cancel', user_path(user), :class => "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>

<table class="table table-hover table-responsive">
  <thead>
  <tr>
    <th>Username</th>
    <th>Team</th>
    <% if can? :delete, User %>
        <th>Actions</th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user_path(user) %></td>
        <td>
          <% if !user.group.nil? %>
              <%= link_to user.group.name, group_path(user.group) %>
          <% end %>
        </td>
        <% if can? :delete, user %>
            <td><%= link_to 'Destroy', user, :class => "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, :class => "btn btn-default" %>

app/views/users/new.html.erb
<% provide(:title, "Signup!") %>
<h1>Signup!</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for :user, url: '/users' do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <%= @user.username %>
</h1>

<% if !@user.group.nil? %>
    <p>
      <strong>Team:</strong>
      <%= @user.group.name %>
    </p>
<% end %>

<h3>Users Issues:</h3>
<table class="table table-hover table-responsive">
  <thead>
  <tr>
    <th>Issue Name</th>
    <th>Project</th>
    <th>Priority</th>
    <th>Status</th>
  </tr>
  </thead>

  <tbody>
  <% @user.issues.each do |issue| -%>
      <tr>
        <td><%= link_to issue.name, issue_path(issue) %></td>
        <td><%= issue.project.name %></td>
        <td><%= issue.priority %></td>
        <td><%= issue.status.name %></td>
      </tr>
  <% end -%>
  </tbody>
</table>
<% if can? :update, @user %>
    <%= link_to 'Edit', edit_user_path(@user), :class => "btn btn-default" %>
<% end %>
<% if can? :delete, @user %>
    <td><%= link_to 'Destroy', @user, :class => "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %></td>
<% end %>

app/views/users/show_issues.html.erb
<p id="notice"><%= notice %></p>
<h1>My Issues</h1>
<table class="table table-hover table-responsive">
  <thead>
  <tr>
    <th>Issue name</th>
    <th>Project</th>
    <th>Priority</th>
    <th>Status</th>
    <th>Actions:</th>
  </tr>
  </thead>

  <tbody>
  <% @issues.each do |issue| -%>
      <tr>
        <td><%= link_to issue.name, issue_path(issue) %></td>
        <td><%= issue.project.name %></td>
        <td><%= issue.priority %></td>
        <td><%= issue.status.name %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue), :class => "btn btn-default" %>
          <% if can? :delete, issue %>
              <%= link_to 'Destroy', issue, :class => "btn btn-danger", method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </td>
      </tr>
  <% end -%>
  </tbody>
</table>