config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#show_issues'

  resources :issues do
    resources :comments
  end
  resources :statuses
  resources :users do
    resources :issues
  end
  resources :projects
  resources :groups do
    resources :users
  end

  get '/issues/:id/edit_status' => 'issues#edit_status', as: 'edit_issue_status'
  put '/issues/:id/change_status' => 'issues#change_status', as: 'change_issue_status'
  put '/working_ons/:id/change_assignee' => 'working_ons#change_assignee', as: 'change_assignee'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get 'users/:id/show_issues' => 'users#show_issues', as: 'show_issues'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jira</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if content_for?(:navbar) %>
    <%= yield(:navbar) %>
<% else %>
    <nav class="navbar-static-top navbar-inverse">
      <div class="container-fluid">
        <%= link_to "Jira -1.0", '/', id: "logo" %>
        <ul class="nav nav-pills navbar-right">
          <% if !current_user.nil? %>
              <li>
                <%= link_to 'My Issues', root_path %>
              </li>
              <% if !current_user.group.nil? %>
                  <li>
                    <%= link_to 'My Team', group_path(current_user.group) %>
                  </li>
              <% end %>
              <li>
                <%= link_to 'Teams', groups_path %>
              </li>
              <li>
                <%= link_to 'Projects', projects_path(current_user) %>
              </li>
              <li>
                <%= link_to 'Users', users_path %>
              </li>
              <% if current_user.admin? %>
                  <li>
                    <%= link_to 'Statuses', statuses_path %>
                  </li>
                  <li>
                    <%= link_to 'Issues', issues_path %>
                  </li>
              <% end %>
              <li>
                <%= link_to 'Create new issue', new_issue_path, :class => "btn btn-primary" %>
              </li>

              <li>
                <%= link_to 'logout', logout_path, :class => "btn btn-danger" %>
              </li>
          <% else %>
              <li>
                <%= link_to 'login', login_path, :class => "btn btn-success" %>
              </li>
          <% end %>

        </ul>
        <ul class="nav nav-pills navbar-right">

        </ul>
      </div>
    </nav>
<% end %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>